on: push
name: CI

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.0

    steps:
      - uses: actions/checkout@v2

      - name: Install composer dependencies
        run: |
          composer install --prefer-dist --no-interaction --no-scripts

      - name: Run Testsuite
        run: vendor/bin/phpunit tests/
